// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IndirectInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "IndirectInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace saib {

namespace {

const ::google::protobuf::Descriptor* IndirectBrTarget_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  IndirectBrTarget_reflection_ = NULL;
const ::google::protobuf::Descriptor* IndirectBrTargetSet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  IndirectBrTargetSet_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_IndirectInfo_2eproto() {
  protobuf_AddDesc_IndirectInfo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "IndirectInfo.proto");
  GOOGLE_CHECK(file != NULL);
  IndirectBrTarget_descriptor_ = file->message_type(0);
  static const int IndirectBrTarget_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IndirectBrTarget, inst_addr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IndirectBrTarget, inst_target_),
  };
  IndirectBrTarget_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      IndirectBrTarget_descriptor_,
      IndirectBrTarget::default_instance_,
      IndirectBrTarget_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IndirectBrTarget, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IndirectBrTarget, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(IndirectBrTarget));
  IndirectBrTargetSet_descriptor_ = file->message_type(1);
  static const int IndirectBrTargetSet_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IndirectBrTargetSet, indirect_info_),
  };
  IndirectBrTargetSet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      IndirectBrTargetSet_descriptor_,
      IndirectBrTargetSet::default_instance_,
      IndirectBrTargetSet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IndirectBrTargetSet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IndirectBrTargetSet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(IndirectBrTargetSet));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_IndirectInfo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    IndirectBrTarget_descriptor_, &IndirectBrTarget::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    IndirectBrTargetSet_descriptor_, &IndirectBrTargetSet::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_IndirectInfo_2eproto() {
  delete IndirectBrTarget::default_instance_;
  delete IndirectBrTarget_reflection_;
  delete IndirectBrTargetSet::default_instance_;
  delete IndirectBrTargetSet_reflection_;
}

void protobuf_AddDesc_IndirectInfo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022IndirectInfo.proto\022\004saib\":\n\020IndirectBr"
    "Target\022\021\n\tinst_addr\030\001 \002(\004\022\023\n\013inst_target"
    "\030\002 \003(\004\"D\n\023IndirectBrTargetSet\022-\n\rindirec"
    "t_info\030\001 \003(\0132\026.saib.IndirectBrTarget", 156);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "IndirectInfo.proto", &protobuf_RegisterTypes);
  IndirectBrTarget::default_instance_ = new IndirectBrTarget();
  IndirectBrTargetSet::default_instance_ = new IndirectBrTargetSet();
  IndirectBrTarget::default_instance_->InitAsDefaultInstance();
  IndirectBrTargetSet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_IndirectInfo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_IndirectInfo_2eproto {
  StaticDescriptorInitializer_IndirectInfo_2eproto() {
    protobuf_AddDesc_IndirectInfo_2eproto();
  }
} static_descriptor_initializer_IndirectInfo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int IndirectBrTarget::kInstAddrFieldNumber;
const int IndirectBrTarget::kInstTargetFieldNumber;
#endif  // !_MSC_VER

IndirectBrTarget::IndirectBrTarget()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void IndirectBrTarget::InitAsDefaultInstance() {
}

IndirectBrTarget::IndirectBrTarget(const IndirectBrTarget& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void IndirectBrTarget::SharedCtor() {
  _cached_size_ = 0;
  inst_addr_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

IndirectBrTarget::~IndirectBrTarget() {
  SharedDtor();
}

void IndirectBrTarget::SharedDtor() {
  if (this != default_instance_) {
  }
}

void IndirectBrTarget::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* IndirectBrTarget::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return IndirectBrTarget_descriptor_;
}

const IndirectBrTarget& IndirectBrTarget::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_IndirectInfo_2eproto();
  return *default_instance_;
}

IndirectBrTarget* IndirectBrTarget::default_instance_ = NULL;

IndirectBrTarget* IndirectBrTarget::New() const {
  return new IndirectBrTarget;
}

void IndirectBrTarget::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    inst_addr_ = GOOGLE_ULONGLONG(0);
  }
  inst_target_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool IndirectBrTarget::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 inst_addr = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &inst_addr_)));
          set_has_inst_addr();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_inst_target;
        break;
      }

      // repeated uint64 inst_target = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_inst_target:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 16, input, this->mutable_inst_target())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_inst_target())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_inst_target;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void IndirectBrTarget::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint64 inst_addr = 1;
  if (has_inst_addr()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->inst_addr(), output);
  }

  // repeated uint64 inst_target = 2;
  for (int i = 0; i < this->inst_target_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      2, this->inst_target(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* IndirectBrTarget::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint64 inst_addr = 1;
  if (has_inst_addr()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->inst_addr(), target);
  }

  // repeated uint64 inst_target = 2;
  for (int i = 0; i < this->inst_target_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(2, this->inst_target(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int IndirectBrTarget::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 inst_addr = 1;
    if (has_inst_addr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->inst_addr());
    }

  }
  // repeated uint64 inst_target = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->inst_target_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->inst_target(i));
    }
    total_size += 1 * this->inst_target_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void IndirectBrTarget::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const IndirectBrTarget* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const IndirectBrTarget*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void IndirectBrTarget::MergeFrom(const IndirectBrTarget& from) {
  GOOGLE_CHECK_NE(&from, this);
  inst_target_.MergeFrom(from.inst_target_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_inst_addr()) {
      set_inst_addr(from.inst_addr());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void IndirectBrTarget::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IndirectBrTarget::CopyFrom(const IndirectBrTarget& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IndirectBrTarget::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void IndirectBrTarget::Swap(IndirectBrTarget* other) {
  if (other != this) {
    std::swap(inst_addr_, other->inst_addr_);
    inst_target_.Swap(&other->inst_target_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata IndirectBrTarget::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = IndirectBrTarget_descriptor_;
  metadata.reflection = IndirectBrTarget_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int IndirectBrTargetSet::kIndirectInfoFieldNumber;
#endif  // !_MSC_VER

IndirectBrTargetSet::IndirectBrTargetSet()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void IndirectBrTargetSet::InitAsDefaultInstance() {
}

IndirectBrTargetSet::IndirectBrTargetSet(const IndirectBrTargetSet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void IndirectBrTargetSet::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

IndirectBrTargetSet::~IndirectBrTargetSet() {
  SharedDtor();
}

void IndirectBrTargetSet::SharedDtor() {
  if (this != default_instance_) {
  }
}

void IndirectBrTargetSet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* IndirectBrTargetSet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return IndirectBrTargetSet_descriptor_;
}

const IndirectBrTargetSet& IndirectBrTargetSet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_IndirectInfo_2eproto();
  return *default_instance_;
}

IndirectBrTargetSet* IndirectBrTargetSet::default_instance_ = NULL;

IndirectBrTargetSet* IndirectBrTargetSet::New() const {
  return new IndirectBrTargetSet;
}

void IndirectBrTargetSet::Clear() {
  indirect_info_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool IndirectBrTargetSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .saib.IndirectBrTarget indirect_info = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_indirect_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_indirect_info()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_indirect_info;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void IndirectBrTargetSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .saib.IndirectBrTarget indirect_info = 1;
  for (int i = 0; i < this->indirect_info_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->indirect_info(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* IndirectBrTargetSet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .saib.IndirectBrTarget indirect_info = 1;
  for (int i = 0; i < this->indirect_info_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->indirect_info(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int IndirectBrTargetSet::ByteSize() const {
  int total_size = 0;

  // repeated .saib.IndirectBrTarget indirect_info = 1;
  total_size += 1 * this->indirect_info_size();
  for (int i = 0; i < this->indirect_info_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->indirect_info(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void IndirectBrTargetSet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const IndirectBrTargetSet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const IndirectBrTargetSet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void IndirectBrTargetSet::MergeFrom(const IndirectBrTargetSet& from) {
  GOOGLE_CHECK_NE(&from, this);
  indirect_info_.MergeFrom(from.indirect_info_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void IndirectBrTargetSet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IndirectBrTargetSet::CopyFrom(const IndirectBrTargetSet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IndirectBrTargetSet::IsInitialized() const {

  for (int i = 0; i < indirect_info_size(); i++) {
    if (!this->indirect_info(i).IsInitialized()) return false;
  }
  return true;
}

void IndirectBrTargetSet::Swap(IndirectBrTargetSet* other) {
  if (other != this) {
    indirect_info_.Swap(&other->indirect_info_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata IndirectBrTargetSet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = IndirectBrTargetSet_descriptor_;
  metadata.reflection = IndirectBrTargetSet_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace saib

// @@protoc_insertion_point(global_scope)
