// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IndirectInfo.proto

#ifndef PROTOBUF_IndirectInfo_2eproto__INCLUDED
#define PROTOBUF_IndirectInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace saib {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_IndirectInfo_2eproto();
void protobuf_AssignDesc_IndirectInfo_2eproto();
void protobuf_ShutdownFile_IndirectInfo_2eproto();

class IndirectBrTarget;
class IndirectBrTargetSet;

// ===================================================================

class IndirectBrTarget : public ::google::protobuf::Message {
 public:
  IndirectBrTarget();
  virtual ~IndirectBrTarget();

  IndirectBrTarget(const IndirectBrTarget& from);

  inline IndirectBrTarget& operator=(const IndirectBrTarget& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IndirectBrTarget& default_instance();

  void Swap(IndirectBrTarget* other);

  // implements Message ----------------------------------------------

  IndirectBrTarget* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IndirectBrTarget& from);
  void MergeFrom(const IndirectBrTarget& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 inst_addr = 1;
  inline bool has_inst_addr() const;
  inline void clear_inst_addr();
  static const int kInstAddrFieldNumber = 1;
  inline ::google::protobuf::uint64 inst_addr() const;
  inline void set_inst_addr(::google::protobuf::uint64 value);

  // repeated uint64 inst_target = 2;
  inline int inst_target_size() const;
  inline void clear_inst_target();
  static const int kInstTargetFieldNumber = 2;
  inline ::google::protobuf::uint64 inst_target(int index) const;
  inline void set_inst_target(int index, ::google::protobuf::uint64 value);
  inline void add_inst_target(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      inst_target() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_inst_target();

  // @@protoc_insertion_point(class_scope:saib.IndirectBrTarget)
 private:
  inline void set_has_inst_addr();
  inline void clear_has_inst_addr();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 inst_addr_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > inst_target_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_IndirectInfo_2eproto();
  friend void protobuf_AssignDesc_IndirectInfo_2eproto();
  friend void protobuf_ShutdownFile_IndirectInfo_2eproto();

  void InitAsDefaultInstance();
  static IndirectBrTarget* default_instance_;
};
// -------------------------------------------------------------------

class IndirectBrTargetSet : public ::google::protobuf::Message {
 public:
  IndirectBrTargetSet();
  virtual ~IndirectBrTargetSet();

  IndirectBrTargetSet(const IndirectBrTargetSet& from);

  inline IndirectBrTargetSet& operator=(const IndirectBrTargetSet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IndirectBrTargetSet& default_instance();

  void Swap(IndirectBrTargetSet* other);

  // implements Message ----------------------------------------------

  IndirectBrTargetSet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IndirectBrTargetSet& from);
  void MergeFrom(const IndirectBrTargetSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .saib.IndirectBrTarget indirect_info = 1;
  inline int indirect_info_size() const;
  inline void clear_indirect_info();
  static const int kIndirectInfoFieldNumber = 1;
  inline const ::saib::IndirectBrTarget& indirect_info(int index) const;
  inline ::saib::IndirectBrTarget* mutable_indirect_info(int index);
  inline ::saib::IndirectBrTarget* add_indirect_info();
  inline const ::google::protobuf::RepeatedPtrField< ::saib::IndirectBrTarget >&
      indirect_info() const;
  inline ::google::protobuf::RepeatedPtrField< ::saib::IndirectBrTarget >*
      mutable_indirect_info();

  // @@protoc_insertion_point(class_scope:saib.IndirectBrTargetSet)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::saib::IndirectBrTarget > indirect_info_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_IndirectInfo_2eproto();
  friend void protobuf_AssignDesc_IndirectInfo_2eproto();
  friend void protobuf_ShutdownFile_IndirectInfo_2eproto();

  void InitAsDefaultInstance();
  static IndirectBrTargetSet* default_instance_;
};
// ===================================================================


// ===================================================================

// IndirectBrTarget

// required uint64 inst_addr = 1;
inline bool IndirectBrTarget::has_inst_addr() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IndirectBrTarget::set_has_inst_addr() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IndirectBrTarget::clear_has_inst_addr() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IndirectBrTarget::clear_inst_addr() {
  inst_addr_ = GOOGLE_ULONGLONG(0);
  clear_has_inst_addr();
}
inline ::google::protobuf::uint64 IndirectBrTarget::inst_addr() const {
  return inst_addr_;
}
inline void IndirectBrTarget::set_inst_addr(::google::protobuf::uint64 value) {
  set_has_inst_addr();
  inst_addr_ = value;
}

// repeated uint64 inst_target = 2;
inline int IndirectBrTarget::inst_target_size() const {
  return inst_target_.size();
}
inline void IndirectBrTarget::clear_inst_target() {
  inst_target_.Clear();
}
inline ::google::protobuf::uint64 IndirectBrTarget::inst_target(int index) const {
  return inst_target_.Get(index);
}
inline void IndirectBrTarget::set_inst_target(int index, ::google::protobuf::uint64 value) {
  inst_target_.Set(index, value);
}
inline void IndirectBrTarget::add_inst_target(::google::protobuf::uint64 value) {
  inst_target_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
IndirectBrTarget::inst_target() const {
  return inst_target_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
IndirectBrTarget::mutable_inst_target() {
  return &inst_target_;
}

// -------------------------------------------------------------------

// IndirectBrTargetSet

// repeated .saib.IndirectBrTarget indirect_info = 1;
inline int IndirectBrTargetSet::indirect_info_size() const {
  return indirect_info_.size();
}
inline void IndirectBrTargetSet::clear_indirect_info() {
  indirect_info_.Clear();
}
inline const ::saib::IndirectBrTarget& IndirectBrTargetSet::indirect_info(int index) const {
  return indirect_info_.Get(index);
}
inline ::saib::IndirectBrTarget* IndirectBrTargetSet::mutable_indirect_info(int index) {
  return indirect_info_.Mutable(index);
}
inline ::saib::IndirectBrTarget* IndirectBrTargetSet::add_indirect_info() {
  return indirect_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::saib::IndirectBrTarget >&
IndirectBrTargetSet::indirect_info() const {
  return indirect_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::saib::IndirectBrTarget >*
IndirectBrTargetSet::mutable_indirect_info() {
  return &indirect_info_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace saib

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_IndirectInfo_2eproto__INCLUDED
